### ISSUE TITLE
how to replace RKRequestQueue?

### ISSUE THREAD

**Issue by haemi** [RestKit/RestKit#1002]
RKRequestQueue isn't supported any more; but how to replace it? NSOperationQueue is one method, but it's pretty difficult because of a weird behaviour:

RKObjectLoader *loader = [[RKObjectManager sharedManager] loaderWithResourcePath:resourcePath];
loader.delegate = self;
[loader sendAsynchronously];

doesn't call the delegate methods, only loadObjectsAtResourcePath:delegate: does. So what's best practice to replace the RKRequestQueue?

**Comment by haxpor** [comment]
@blakewatters Does this mean the latest version of Restkit although without `RKRequestQueue` anymore can still perform as a gate keeper to send request behind the scene? Also when the network is down, whenever it comes back it will try to send those requests again?

Because I'm pretty much this those kind of functionality as I've seen in [this](http://code.tutsplus.com/tutorials/ios-sdk-advanced-restkit-development--mobile-5916).
