### ISSUE TITLE
Property 'managedObjectStore' not found on object of type 'RKObjectManager *'

### ISSUE THREAD

**Issue by crspratt** [RestKit/RestKit#1602]
I've been searching for a resolution to this error for about five days now. I performed all cocoapod install requirements for my project. Everything seems to work fine but this error doesn't make any sense. 

Please provide some assistance if you can.

```
RKObjectManager *objectManager = [RKObjectManager managerWithBaseURL:baseURL];

//let AFNetworking manage the activity indicator
[AFNetworkActivityIndicatorManager sharedManager].enabled = YES;

//Initialize managed object store
NSManagedObjectModel *managedObjectModel = [NSManagedObjectModel mergedModelFromBundles:nil];
RKManagedObjectStore *managedObjectStore = [[RKManagedObjectStore alloc] initWithManagedObjectModel:managedObjectModel];

objectManager.managedObjectStore = managedObjectStore;

// Setup our object mappings
/**
 Mapping by entity. Here we are configuring a maping by targetting a Core Data entity with a specific
 name. This allows us to map back Sensor database objects directly onto NSManagedObject instances
 there is no backing model class
 */
RKEntityMapping *sensorMapping = [RKEntityMapping mappingForEntityForName:@"SensorID" inManagedObjectStore:managedObjectStore];
sensorMapping.identificationAttributes = @[ @"sensorID"];
[sensorMapping addAttributeMappingsFromDictionary:@{
        @"sensorID" : @"sensorID",
        @"cellNum"  : @"cellNum",
        @"timeStamp": @"timeStamp",
        @"temp"     : @"temp"
        }];
```

**Comment by jim3ex** [comment]
The root cause of this issue is in RKObjectmanager.h

#ifdef _COREDATADEFINES_H
#   if __has_include("RKCoreData.h")
#       define RKCoreDataIncluded
#   endif
#endif

This include has changed names so everywhere RKCoreData.h appears change to RestKit/CoreData.h there are several include files that use this construct so do a global search.

**Comment by mvoelkl** [comment]
Hi all!

We also had this issue after updating to CocoaPods 0.39. According to http://stackoverflow.com/a/33240398/1365370 this is a problem of CocoaPods and can be fixed by adding _${PODS_ROOT}_ (as _Recursive_) to _Header Search Path_ in Build Settings.

Hope this helps everyone who discovers this issue!

**Comment by ostatnicky** [comment]
@mvoelkl: It works for me. Thanks!

**Comment by cassianomonteiro** [comment]
This isn't working for me on XCode 8.1 ... There is no pch file anymore, and CocoaPods 1.1.1 already adds all paths to the Header Search path. Any hints?

**Comment by telipskiy** [comment]
I have the same issue as @cassianomonteiro posted. I tried diff solutions, but error still there...

**Comment by cassianomonteiro** [comment]
@telipskiy It seems to be a bug from version 0.26.0. I werked around by adding this on top of my files using managedObjectStore:

`
// Workaround for bug on RestKit 0.26.0 according to https://github.com/RestKit/RestKit/issues/2352
#ifndef RKCoreDataIncluded
#define RKCoreDataIncluded
#endif
`

**Comment by telipskiy** [comment]
@cassianomonteiro, thank you
