### ISSUE TITLE
Artificial identification attributes

### ISSUE THREAD

**Issue by DZamataev** [RestKit/RestKit#1604]
linked [Stackoverflow question #18874384](http://stackoverflow.com/questions/18874384/ios-restkit-artificial-identification-attributes)

If my API gives me no `id` attribute, but i still want to cache the objects via Core Data, what should i use to identify my object.
For example i have

```
translation =     {
        text = "check";
        dictionary = "general";
        lang = "en";
    };
```

So i would be glad to use hashed (md5) text as an id string.
Notice that my future requests which happen without network connection should be able to identify this cached entity and give it as a result.

I cant declare mapping to fill `translationID` property from `[text md5hash]` to use as `translationMapping.identificationAttributes = @[ translationID ];`

**Comment by mplorentz** [comment]
I'm trying to create an artificial identification attribute computed based on a relationship. Something like this: I have a Person object with JSON like so 
```
{
    'name': 'Joe',
    'addresses': [
        {
            'addressID': 1
        }
    ]
}
```
And I want the identificationAttributes for my person to be the name and the addressID. So I make a property called `primaryAddressID` on my Person and I set it in `willSave` to be the first `addressID` I can find on the Person.

Even after implementing this if I get two people with the same `name` but different `addressID`s only one person makes it into Core Data. Is this because the relationships are not being set until after the identification attributes have been fetched? Does anyone know of a solution to this?
