### ISSUE TITLE
NSNull tried to be inserted to NSString property (or String in Swift)

### ISSUE THREAD

**Issue by bimusiek** [RestKit/RestKit#2155]
I recently upgraded RestKit to latest version and I am getting crashes when RestKit tries to setValue for NSString as [NSNull null]

I investigated issue and in new version there is new checking for parsing values

    // Always set the properties
    if (self.shouldSetUnchangedValues) {
        return [self validateValue:value atKeyPath:keyPath];
    }

And in validate value there is this code which asks `destinationObject` to validate property

	if ([destinationObject respondsToSelector:@selector(validateValue:forKeyPath:error:)]) {
		NSError *validationError;
		success = [destinationObject validateValue:value forKeyPath:keyPath error:&validationError];

Unfortunately `Swift` accept `NSNull` into `NSString` and then app crashes.

I patched it for myself in `destinationObject` like this:

    public override func validateValue(ioValue: AutoreleasingUnsafeMutablePointer<AnyObject?>, forKeyPath inKeyPath: String, error outError: NSErrorPointer) -> Bool {
        if let memory = ioValue.memory {
            if inKeyPath == "hint" && ioValue.memory is NSNull {
                ioValue.memory = nil
                return true
            }
        }
        return super.validateValue(ioValue, forKeyPath: inKeyPath, error: outError)
    }

But that is not perfect solution. Any ideas how to properly fix it? I am not so into RestKit, so I don't know where to patch it. Basically it is bug in NSObject I think, because it accepts this value.

BTW. I guess I am not the only one with an issue.
http://stackoverflow.com/questions/27917104/restkit-json-null-value-crash/28350423#28350423

If you would tell me where could I work on patch (validateValue or check if shouldSetUnchangedValues?) I can do it over weekend.

**Comment by bimusiek** [comment]
I have fix for it but to write test I would have to write it in Swift, which implicates more things like enabling project for iOS 7.0 and newer.

**Comment by segiddins** [comment]
RestKit does not do anything special for swift subclasses of NSObject at the moment.

GitHub Issues is for reporting bugs in RestKit and discussing changes to RestKit itself. Please check the [documentation](http://cocoadocs.org/docsets/RestKit/), [wiki](https://github.com/RestKit/RestKit/wiki), and [existing issues](https://github.com/RestKit/RestKit/issues?state=closed) before opening a new issue.

Additionally, please do not post general usage questions to Issues, but instead take them to [Stack Overflow](http://stackoverflow.com/questions/tagged/restkit).

**Comment by brightredchilli** [comment]
I know this issue is closed, but I'm putting this out here in case it might help anyone. The reason this is happening is because Restkit cannot introspect Swift classes to figure out the the type of a property.(0.24.1).

In Objective-C, the `- (Class)classForKeyPath:(NSString *)keyPath` method on RKObjectMapping will return the proper class, whereas in Swift, it returns nil. This can be traced further down to `- (NSDictionary *)propertyInspectionForClass:(Class)objectClass` not returning the proper values.

In RKObjectMappingOperation.m:
````
    Class transformedValueClass = propertyMapping.propertyValueClass ?: [self.objectMapping classForKeyPath:propertyMapping.destinationKeyPath];
    if (! transformedValueClass) {
        *outputValue = inputValue;
        return YES;
    }
````

Because transformedValueClass will always be nil, this causes inputValue to just get assigned to outputValue, ie, NSNull would get assigned to an NSString property.

I have a workaround, documented here(http://stackoverflow.com/a/32279307/175225). The jist of it is to create an RKAttributeMapping with a propertyValueClass defined:

````
let simpleMapping = RKAttributeMapping(fromKeyPath: "first_name", toKeyPath: "firstName")
simpleMapping.propertyValueClass = NSString.classForCoder()
````
I have tested that this causes a null json value to be mapped to nil properly. Haven't tested non-optional properties yet.
