### ISSUE TITLE
Upgrade AFNetworking dependency?

### ISSUE THREAD

**Issue by biddster** [RestKit/RestKit#2207]
Just highlighting this security issue, http://sourcedna.com/blog/20150424/afnetworking-strikes-back.html.

Suggests that any version prior to 2.5.3 has the issue. I think RestKit uses 1.3.0?

**Comment by segiddins** [comment]
RestKit is currently locked to the 1.3 series of afnetworking releases.

**Comment by bioche** [comment]
Any idea on when you plan to do the migration ? I read somewhere that you wanted to get rid of AFNetWorking for RestKit. Is that still on top of your list ? (Clients are starting to be concerned with security issues about using an outdated version of AFNetWorking and I don't have time to start over with another API ...) Thanks

**Comment by segiddins** [comment]
@bioche it is on the list of things we'd _like_ to do, but it's a massive undertaking, especially since I no longer use RestKit in my day job.

**Comment by blakewatters** [comment]
Note that the AFNetworking security issue only affected v2.0 and higher clients. It won’t affect apps using RestKit.

**Comment by bioche** [comment]
Ok thanks for your quick comment ! Restkit worked great aside from this security issue.

**Comment by bioche** [comment]
Thank you both for your quick answers :) I'll keep using it for now, it works great !

**Comment by biddster** [comment]
Thanks for the clarification chaps.

**Comment by natecode** [comment]
@blakewatters That's not the case, unfortunately. 1.2.0 - 1.3.4 are vulnerable too.

Issue: https://github.com/AFNetworking/AFNetworking/issues/2690

**Comment by kcharwood** [comment]
We have now closed the issue. The original issue was reported in error due to how a test was configured, and we have been unable to reproduce any additional security vulnerabilities. Multiple parties have confirmed domain validation in 1.3.4 is working as expected, so users of RestKit should not worry about any issues with AF.

Please see [#2690](https://github.com/AFNetworking/AFNetworking/issues/2690) for further discussion.

:beers:
