### ISSUE TITLE
SSL validation flaw in AFNetworking 1.3.x in RestKit

### ISSUE THREAD

**Issue by natecode** [RestKit/RestKit#2209]
The embedded AFNetworking library in RestKit does not validate cert domain names, and is thus vulnerable to MITM attacks. This issue is mitigated if the caller has enabled cert or public key pinning, but I am not sure if RestKit does this as we haven't fully reviewed and tested it yet.

Issue: https://github.com/AFNetworking/AFNetworking/issues/2690

**Comment by segiddins** [comment]
We need an afnetworking update to the 1.3.x series to fix that.

**Comment by natecode** [comment]
So you can't leave the issue open, pending a fix from upstream?

**Comment by segiddins** [comment]
There's nothing for RestKit to do -- that code lives entirely in the afnetworking dependency.

**Comment by cossorn** [comment]
Please refer to my latest comment in issue 2208. The issue of checking the domain of the URL request vs the domain that is in the certificate exists in AFNetworking 1.3.4, which is resolved in AFNetworking 2.5.3. The issue remains that current RestKit has a dependency, which can be fixed in RestKit.

**Comment by segiddins** [comment]
Yes, but the amount of effort required to rewrite a huge part of restkit versus backporting a fix in AFNetworking is astronomical.

**Comment by segiddins** [comment]
The AFNetworking team has directly reached out to inform us they are actively working on resolving all security issues in the 1.x release. Once the issues have been resolved, they will cut a new release which will automatically be picked up by RestKit due to the nature of the podspec structure. We will keep this ticket open and closely monitor the progress of AFNetworking #2690.

**Comment by natecode** [comment]
@segiddins That's great to hear. I apologize for any friction in communication as we are absolutely swamped with the coordination required.

**Comment by kcharwood** [comment]
I wanted to drop by and provide an update to this thread. 

The original issue that was created appears to have been created in error due to a misconfiguration in a test. At the moment, there are no known, reproducible security vulnerabilities in AFN 1.3.4. There is one user who has reported a possible issue in the same github ticket, but that issue has not been verified or reproduced. We are currently awaiting more information to determine if there is an actual issue to investigate on that front.

You can continue to monitor progress [here](https://github.com/AFNetworking/AFNetworking/issues/2690), and if an issue is verified and uncovered, we'll be sure to keep RestKit users up to date.

**Comment by kcharwood** [comment]
We have now closed the issue. The original issue was reported in error due to how a test was configured, and we have been unable to reproduce any additional security vulnerabilities. Multiple parties have confirmed domain validation in 1.3.4 is working as expected, so users of RestKit should not worry about any issues with AF.

This issue can be closed. Please see [#2690](https://github.com/AFNetworking/AFNetworking/issues/2690) for further discussion.

:beers:
