### ISSUE TITLE
How to integrate on tvOS?

### ISSUE THREAD

**Issue by maremmle** [RestKit/RestKit#2318]
I know there is already a close issue for tvOS support (#2297). But unfortunately it was closed with no solution (at least not a public one).

Could you please provide some minimum step on how to use RestKit with tvOS? 

Cheers, Martin

**Comment by segiddins** [comment]
First, there will need to be a 1.x version of AFNetworking with tvOS support

**Comment by maremmle** [comment]
Well 

@RyanCodes closed the other issue with the comment of "we chose other options for tvOS". So I am wondering what those are.

**Comment by Mazyod** [comment]
@maremmle I believe it highly depends on how deeply integrated RestKit is in your codebase. For example, in our case we only use RestKit for mapping responses and object caching. We don't utilize the networking functionality at all. 

I will need to find a solution in the next couple of days, but I think forking RestKit, deleting everything we don't need, and adding tvOS support might work well for us.

Will hopefully post back here with a solution.

_(Usually, one should try and help the library developers instead of jumping ship so quickly, but it's sad how tight our deadline is for a tvOS app :( )_
